- id: demo-httpbin
  upstream:
    url: http://httpbin:8080
    strip_path: /demo
  match:
    url: http://localhost:4455/demo/<(get|post)>
    methods:
      - GET
      - POST
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: remote_json
    config:
      remote: http://app:8080/authorization/verify
      payload: |
        {
          "subject": "user:{{ print .Subject }}",
          "object": "document:readme",
          "permission": "read"
        }
  mutators:
    - handler: noop
