serve:
  proxy:
    port: 4455

log:
  level: info

access_rules:
  repositories:
    - file:///etc/oathkeeper/access-rules.yml

authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://app:8080/oauth2/introspect
      scope_strategy: none
      pre_authorization:
        enabled: false

authorizers:
  remote_json:
    enabled: true
    config:
      remote: http://app:8080/authorization/verify
      payload: |
        {}

mutators:
  noop:
    enabled: true

errors:
  handlers:
    json:
      enabled: true
